<%@ Page Language="C#" MasterPageFile="~/MasterPages/SingleColumn.Master" AutoEventWireup="true" CodeBehind="AktaSpraw.aspx.cs" Inherits="Pemi.Esoda.Web.UI.Akta.AktaSpraw" Title="Przegl¹danie akt spraw" %>
<asp:Content ID="Content2" ContentPlaceHolderID="main" runat="server">
<h2><%=Page.Title%></h2>
<div id="leftNarrowColumn">
<asp:LinkButton ID="lnkReturn" Visible="false" runat="server" Text="Powrót" PostBackUrl="~/Aplikacje/PanelAdministracyjny/edycjaTeczek.aspx" />
<h3>Lista teczek</h3>
<fieldset>
<legend>Filtrowanie</legend>

<table border="0">
<tr><td><asp:Label ID="lbl1" runat="server" AssociatedControlID="rok" Text="Wybierz rok" />
<asp:DropDownList runat="Server" ID="rok" AutoPostBack="True" />
    <br />
<asp:Label ID="lbl2" runat="server" Text="Wyœwietl od:" AssociatedControlID="ddlShowFrom" />
<asp:DropDownList ID="ddlShowFrom" runat="server" AutoPostBack="true">
    <asp:ListItem Text="wszystkie" Value="" Selected="True"></asp:ListItem>
    <asp:ListItem>0</asp:ListItem>
    <asp:ListItem>1</asp:ListItem>
    <asp:ListItem>2</asp:ListItem>
    <asp:ListItem>3</asp:ListItem>
    <asp:ListItem>4</asp:ListItem>
    <asp:ListItem>5</asp:ListItem>
    <asp:ListItem>6</asp:ListItem>
    <asp:ListItem>7</asp:ListItem>
    <asp:ListItem>8</asp:ListItem>
    <asp:ListItem>9</asp:ListItem>
</asp:DropDownList>
<asp:RadioButtonList ID="rblOwnerSelect" runat="server" RepeatDirection="Vertical" AutoPostBack="true">
<asp:ListItem Text="Moje" Value="True"></asp:ListItem>
<asp:ListItem Text="Wydzia³owe" Value="False" Selected="True"></asp:ListItem>
</asp:RadioButtonList>

<asp:CheckBox runat="server" id="showArchive" Text="Archiwalne" AutoPostBack="true" /></td>
</tr>
</table>


</fieldset>
<asp:TreeView ID="drzewoTeczek" runat="server" AutoGenerateDataBindings="False" 
        onselectednodechanged="drzewoTeczek_SelectedNodeChanged" 
        EnableViewState="False" ShowLines="True" ExpandDepth="0">
    <DataBindings>
        <asp:TreeNodeBinding DataMember="teczka" ValueField="id" TextField="sygnatura" ToolTipField="tytul" SelectAction="SelectExpand" />
    </DataBindings>
</asp:TreeView>
<asp:XmlDataSource ID="xmldsGrupyTeczek" runat="server" EnableCaching="False" 
        XPath="teczki/teczka">
</asp:XmlDataSource>
<%--<hr />--%>
<asp:GridView runat="server" Visible="false" ID="listaTeczek" CssClass="fullWidth grid gridSprawa" 
        GridLines="None" AllowPaging="True" AutoGenerateColumns="False" 
        DataKeyNames="id" DataSourceID="ObjectDataSource1" 
        OnSelectedIndexChanged="listaTeczek_SelectedIndexChanged" AllowSorting="True" 
        PageSize="20" OnDataBound="listaTeczek_DataBound" 
        ondatabinding="listaTeczek_DataBinding" >
  <Columns>
    <asp:ButtonField CommandName="Select" DataTextField="przyrostek" HeaderText="Symbol JRWA" SortExpression="przyrostek"/>
    <asp:BoundField HeaderText="Kom. org." DataField="skrot" />
     <asp:ButtonField CommandName="Select" DataTextField="tytul" HeaderText="Tytu³" SortExpression="tytul" />
  </Columns>
  <PagerSettings Mode="NextPreviousFirstLast" />
  <SelectedRowStyle CssClass="wybrany" />
  <EmptyDataTemplate>Brak akt spraw spe³niaj¹cych podane kryteria.</EmptyDataTemplate>
</asp:GridView>
  <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" OldValuesParameterFormatString="original_{0}"
    SelectMethod="GetBriefcasesFromYear" TypeName="Pemi.Esoda.DataAccess.BriefcaseDAO">
    <SelectParameters>
      <asp:ControlParameter ControlID="rok" DefaultValue="" Name="year" PropertyName="SelectedValue"
        Type="Int32" />                
                  <asp:Parameter Name="userId" Type="Object" />
      <asp:ControlParameter ControlID="ddlShowFrom" Name="beginsWith" PropertyName="SelectedValue"
         Type="String" />
                  <asp:ControlParameter ControlID="rblOwnerSelect" Name="doPracownika" 
            PropertyName="SelectedValue" Type="Boolean"></asp:ControlParameter>
    </SelectParameters>
  </asp:ObjectDataSource>
</div>

<div id="rightWideColumn">
<h3>Informacje o teczce</h3>
<asp:Repeater runat="server" ID="naglowekTeczki">
<ItemTemplate>
<table class="fullWidth grid gridSprawa">
<tr>
<th>Rok</th>
<th>Referent</th>
<th>Symbol kom. org.</th>
<th>Oznaczenie teczki</th>
<th>Tytu³ teczki wg wykazu akt</th>
<th>&nbsp;</th>
</tr>
<tr>
<td><%# XPath("rok") %></td>
<td><%# XPath("osobaOdpowiedzialna") %></td>
<td><%# XPath("symbolWydzialu") %></td>
<td><%# XPath("oznaczenieTeczki") %></td>
<td><%# XPath("tytulTeczki") %></td>
<td><asp:HyperLink runat="server" NavigateUrl='<%# XPath("ID","~/Aplikacje/Raporty/RaportTeczki.aspx?tid={0}") %>' ImageUrl="~/App_Themes/StandardLayout/img/caseReport.png" alt="raport teczki" title="Pobranie raportu o teczce" /></td>
</tr>
</table>
</ItemTemplate>
</asp:Repeater>
<asp:Label runat="Server" ID="briefcaseHeaderStatusMessage" />
<h3>Zawartoœæ teczki</h3>
<asp:Repeater runat="server" ID="listaSpraw" OnItemCommand="listaSpraw_ItemCommand">
<HeaderTemplate>
<table class="grid fullWidth gridSprawa">
<tr>
<th rowspan="2">Lp.</th>
<th rowspan="2">Sprawa<br />(krótka treœæ)</th>
<th colspan="2">Interesant</th>
<th colspan="2">Data</th>
<th rowspan="2">Uwagi<br />(sposób za³atwienia)</th>
<th rowspan="2">Szczegó³y</th>
</tr>
<tr>
<th>Znak pisma</th>
<th>Z dnia</th>
<th>Wszczêcia<br />sprawy</th>
<th>Ostatecznego<br />za³atwienia</th>
</tr>

</HeaderTemplate>

<ItemTemplate>
<tr>
<td rowspan="2"><%# XPath("lp") %></td>
<td rowspan="2"><%# XPath("rodzajSprawy") %></td>
<td colspan="2" style="text-align:center;"><%# (!XPath("nadawca").ToString().Equals("")) ? XPath("nadawca") : "&nbsp;" %></td>
<td rowspan="2"><%# (!XPath("dataWszczecia").Equals("")) ? DateTime.Parse(XPath("dataWszczecia").ToString()).ToString("yyyy-MM-dd") : "" %></td>
<td rowspan="2"><%# (!XPath("dataOstatecznegoZalatwienia").Equals("-") && !XPath("dataOstatecznegoZalatwienia").Equals("")) ? DateTime.Parse(XPath("dataOstatecznegoZalatwienia").ToString()).ToString("yyyy-MM-dd") : "-"%></td>
<td rowspan="2"><%# XPath("sposobZalatwienia") %></td>
<td rowspan="2">
<asp:LinkButton runat="server" CommandName="viewCase" CommandArgument='<%# XPath("idSprawy") %>' Text="zobacz" />
</td>
</tr>
<tr>
<td><%# (!XPath("znakPisma").ToString().Equals("")) ? XPath("znakPisma") : "&nbsp;" %></td>
<td><%# (!XPath("dataPisma").Equals("")) ? DateTime.Parse(XPath("dataPisma").ToString()).ToString("yyyy-MM-dd") : "&nbsp;"%></td>
</tr>
</ItemTemplate>
<AlternatingItemTemplate>
<tr class="pozycjaNieparzysta">
<td rowspan="2"><%# XPath("lp") %></td>
<td rowspan="2"><%# XPath("rodzajSprawy") %></td>
<td colspan="2" style="text-align:center;"><%# (!XPath("nadawca").ToString().Equals("")) ? XPath("nadawca") : "&nbsp;"%></td>
<td rowspan="2"><%# (!XPath("dataWszczecia").Equals("")) ? DateTime.Parse(XPath("dataWszczecia").ToString()).ToString("yyyy-MM-dd") : "" %></td>
<td rowspan="2"><%# (!XPath("dataOstatecznegoZalatwienia").Equals("-") && !XPath("dataOstatecznegoZalatwienia").Equals("")) ? DateTime.Parse(XPath("dataOstatecznegoZalatwienia").ToString()).ToString("yyyy-MM-dd") : "-"%></td>
<td rowspan="2"><%# XPath("sposobZalatwienia") %></td>
<td rowspan="2">
<asp:LinkButton ID="LinkButton1" runat="server" CommandName="viewCase" CommandArgument='<%# XPath("idSprawy") %>' Text="zobacz" />
</td>
</tr>
<tr class="pozycjaNieparzysta">
<td><%# (!XPath("znakPisma").ToString().Equals("")) ? XPath("znakPisma") : "&nbsp;"%></td>
<td><%# (!XPath("dataPisma").Equals("")) ? DateTime.Parse(XPath("dataPisma").ToString()).ToString("yyyy-MM-dd") : "&nbsp;"%></td>
</tr>
</AlternatingItemTemplate>
<FooterTemplate>
</table>
</FooterTemplate>
</asp:Repeater>
<asp:Label runat="Server" ID="briefcaseStatusMessage" />
</div>
</asp:Content>


