<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/MasterPages/SingleColumn.Master"
  Codebehind="edycjaJRWA.aspx.cs" Inherits="Pemi.Esoda.Web.UI.Aplikacje.PanelAdministracyjny.edycjaJRWA"
  Title="Zarz¹dzanie Jednolitym Rzeczowym Wykazem Akt (JRWA)" %>
<%@ Register Src="../../Controls/OperacjePaneluAdministracyjnego.ascx" TagName="OperacjePaneluAdministracyjnego"
  TagPrefix="uc1" %>
<asp:Content ID="Content2" ContentPlaceHolderID="main" runat="server">
  <uc1:OperacjePaneluAdministracyjnego ID="OperacjePaneluAdministracyjnego1" runat="server" />
  <div id="leftColumn" class="ramka">
    <h3>Aktualna struktura JRWA</h3>
    <asp:LinkButton Visible="false" ID="lnkPrint" runat="server" PostBackUrl="~/Aplikacje/PanelAdministracyjny/printJRWA.aspx">Drukowanie</asp:LinkButton>
    <asp:TreeView ID="tvJRWA" runat="server" AutoGenerateDataBindings="False" DataSourceID="dsxmlJRWA"
      LineImagesFolder="~/TreeLineImages" ImageSet="Arrows" OnSelectedNodeChanged="tvJRWA_SelectedNodeChanged"
      ExpandDepth="0" OnPreRender="tvJRWA_PreRender" OnTreeNodeDataBound="tvJRWA_TreeNodeDataBound">
      <DataBindings>
        <asp:TreeNodeBinding DataMember="jrwaItem" TextField="opis" ToolTipField="opis" ValueField="id" TargetField="aktywny" />
      </DataBindings>
      <SelectedNodeStyle CssClass="treeSelectedNode" />
    </asp:TreeView>
    <asp:XmlDataSource ID="dsxmlJRWA" runat="server" XPath="jrwaTree/jrwaItem" EnableCaching="False">
    </asp:XmlDataSource>
  </div>
  <div id="rightColumn">
    <h3>Operacje na strukturze JRWA</h3>
    <fieldset>
      <legend>Eksport danych JRWA</legend>
      <asp:UpdatePanel ID="UpdatePanel2" runat="server">
        <ContentTemplate>
          <asp:LinkButton ID="lnkExportJRWA" Text="Eksportuj" runat="server" CausesValidation="False"
            OnClick="lnkExportJRWA_Click"></asp:LinkButton>
        </ContentTemplate>
        <Triggers>
          <asp:PostBackTrigger ControlID="lnkExportJRWA" />
        </Triggers>
      </asp:UpdatePanel>
    </fieldset>
    <fieldset>
      <legend>Import danych JRWA</legend>
      <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
          <asp:FileUpload ID="fuplJRWA" runat="server" CssClass="longTextBox" /><br />
          <asp:LinkButton ID="lnkImportJRWA" Text="Importuj" runat="server" CausesValidation="False"
            OnClick="lnkImportJRWA_Click"></asp:LinkButton>
        </ContentTemplate>
        <Triggers>
          <asp:PostBackTrigger ControlID="lnkImportJRWA" />
        </Triggers>
      </asp:UpdatePanel>
    </fieldset>
    <asp:Label ID="lblError" runat="server"></asp:Label>
    <asp:Panel ID="pnlTargetJRWA" runat="server" CssClass="ramka" Visible="False">
      <fieldset>
        <legend>Wybór nadrzêdnego JRWA</legend>
        <asp:LinkButton ID="lnkCancel" runat="server" Text="Anuluj" OnClick="lnkCancel_Click" /><br />
        <asp:TreeView ID="tvTargetJRWA" runat="server" ImageSet="Arrows" OnSelectedNodeChanged="tvTargetJRWA_SelectedNodeChanged">
        </asp:TreeView>
      </fieldset>
    </asp:Panel>
    <asp:FormView ID="frmJRWA" runat="server" OnItemInserting="frmJRWA_ItemInserting"
      OnItemUpdating="frmJRWA_ItemUpdating" OnModeChanging="frmJRWA_ModeChanging" OnDataBound="frmJRWA_DataBound">
        <EditItemTemplate>
        <table class="grid fullWidth">
          <tbody>
            <tr>
              <th colspan="2">Edycja pozycji JRWA</th>
            </tr>
            <tr>
              <th>Symbol:</th>
              <td>
                  <asp:Label ID="lblParentSymbol" runat="server" Visible="False"></asp:Label>
                  <asp:TextBox ID="txtSymbol" runat="server" Text='<%# Bind("symbol") %>' 
                      Width="69px" MaxLength="5"><span __designer:mapid="30a">&lt;%# Bind(&quot;symbol&quot;) 
                  %&gt;</span><span __designer:mapid="30a">&lt;%# Bind(&quot;symbol&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;symbol&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# Bind(&quot;symbol&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;symbol&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# Bind(&quot;symbol&quot;) %&gt;</span></asp:TextBox><asp:RequiredFieldValidator
                  ID="rfvSymbol" runat="server" Text="wymagane" ValidationGroup="JRWA" ErrorMessage="*"
                  ControlToValidate="txtSymbol"></asp:RequiredFieldValidator>
                  <asp:RangeValidator ID="rvSymbol" runat="server" ControlToValidate="txtSymbol" Display="Dynamic"
                      Enabled="False" ErrorMessage="*" MaximumValue="9" MinimumValue="0" Type="Integer"
                      ValidationGroup="JRWA">wartoœæ musi byæ z przedzia³u od 0 do 9</asp:RangeValidator></td>
            </tr>
            <tr>
              <th>Nazwa:</th>
              <td>
                <asp:TextBox ID="txtNazwa" runat="server" Text='<%# Bind("nazwa") %>' 
                      Width="250px" MaxLength="500"><span __designer:mapid="30a">&lt;%# Bind(&quot;nazwa&quot;) 
                  %&gt;</span><span __designer:mapid="30a">&lt;%# Bind(&quot;nazwa&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;nazwa&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# Bind(&quot;nazwa&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;nazwa&quot;) %&gt;</span></asp:TextBox><asp:RequiredFieldValidator
                  ID="rfvNazwa" runat="server" Text="wymagane" ValidationGroup="JRWA" ErrorMessage="*"
                  ControlToValidate="txtNazwa"></asp:RequiredFieldValidator></td>
            </tr>
            <tr>
              <th>Kategoria archiwalna<br />
                w kom. macierz.</th>
              <td>
                <asp:TextBox ID="txtKategoriaAKM" runat="server" Text='<%# Bind("kategoriaAKM") %>'
                  Width="170px" MaxLength="10"><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;kategoriaAKM&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;kategoriaAKM&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;kategoriaAKM&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;kategoriaAKM&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;kategoriaAKM&quot;) %&gt;</span></asp:TextBox><asp:RequiredFieldValidator ID="rfvKategoriaAKM" runat="server"
                    Text="wymagane" Visible="False" Enabled="False" ValidationGroup="JRWA" ErrorMessage="*"
                    ControlToValidate="txtKategoriaAKM"></asp:RequiredFieldValidator></td>
            </tr>
            <tr>
              <th>Kategoria archiwalna<br />
                w innych kom.</th>
              <td>
                <asp:TextBox ID="txtKategoriaAIK" runat="server" Text='<%# Bind("kategoriaAIK") %>'
                  Width="170px" MaxLength="10"><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;kategoriaAIK&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;kategoriaAIK&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;kategoriaAIK&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;kategoriaAIK&quot;) %&gt;</span><span __designer:mapid="30a">&lt;%# 
                  Bind(&quot;kategoriaAIK&quot;) %&gt;</span></asp:TextBox><asp:RequiredFieldValidator ID="rfvKategoriaAIK" runat="server"
                    Text="wymagane" Visible="False" Enabled="False" ValidationGroup="JRWA" ErrorMessage="*"
                    ControlToValidate="txtKategoriaAIK"></asp:RequiredFieldValidator></td>
            </tr>
            <tr>
              <th>Uwagi:</th>
              <td>
                <asp:TextBox ID="txtUwagi" runat="server" Text='<%# Bind("uwagi") %>' Width="95%"
                  Rows="3" TextMode="MultiLine" MaxLength="500"></asp:TextBox></td>
            </tr>
            <tr>
              <th>Status:</th>
              <td>
                <asp:CheckBox ID="ckbAktywna" runat="server" Text="Aktywny" Checked='<%# Bind("aktywny") %>'>
                </asp:CheckBox></td>
            </tr>
            <tr>
              <th>
                <asp:Label ID="lblOffset" runat="server" Text="Przenoszenie:"></asp:Label></th>
              <td>
                <table width="100%">
                  <tbody>
                    <tr>
                      <td></td>
                      <td>
                        <asp:LinkButton ID="lnkMove" OnClick="lnkMove_Click" runat="server">Wybierz...</asp:LinkButton>
                          <asp:LinkButton ID="lnkClearParent" runat="server" OnClick="lnkClearParent_Click">Wyczyœæ</asp:LinkButton></td>
                      <td></td>
                    </tr>
                    <tr>
                      <td>
                        <asp:Label ID="Label1" runat="server" Text="Docelowe nadrzêdne JRWA:"></asp:Label></td>
                      <td>
                        <asp:Label ID="lblTargetParentJRWA" runat="server"></asp:Label></td>
                      <td>
                        <asp:HiddenField ID="hfTargetJRWAParentId" runat="server"></asp:HiddenField>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td colspan="2">
                <asp:LinkButton ID="btnUpdate" runat="server" Text="Zapisz" CommandName="Update"
                  ValidationGroup="JRWA"></asp:LinkButton><asp:LinkButton ID="btnCancel" OnClick="btnCancel_Click"
                    runat="server" Text="Anuluj" CausesValidation="False"></asp:LinkButton></td>
            </tr>
          </tbody>
        </table>
        </EditItemTemplate>
        <InsertItemTemplate>
        <table class="grid fullWidth">
          <tbody>
            <tr>
              <th colspan="2">Dodawanie pozycji JRWA</th>
            </tr>
            <tr>
              <th>
                <asp:Label ID="lblSymbol" runat="server" Text="Symbol:" AssociatedControlID="txtSymbol"></asp:Label></th>
              <td>
                <asp:Label ID="lblParentSymbol" runat="server"/><asp:TextBox ID="txtSymbol" runat="server" MaxLength="1" Width="15px"></asp:TextBox><asp:RequiredFieldValidator
                  ID="rfvSymbol" runat="server" Text="wymagane" ValidationGroup="JRWA" ErrorMessage="*"
                  ControlToValidate="txtSymbol" Display="Dynamic"></asp:RequiredFieldValidator>
                  <asp:RangeValidator ID="rvSymbol" runat="server" ControlToValidate="txtSymbol" Display="Dynamic"
                      ErrorMessage="*" MaximumValue="9" MinimumValue="0" Type="Integer" ValidationGroup="JRWA">wartoœæ musi byæ z przedzia³u od 0 do 9</asp:RangeValidator></td>
            </tr>
            <tr>
              <th>
                <asp:Label ID="lblNazwa" runat="server" Text="Nazwa:" AssociatedControlID="txtNazwa"></asp:Label></th>
              <td>
                <asp:TextBox ID="txtNazwa" runat="server" Width="200px" MaxLength="500"></asp:TextBox><asp:RequiredFieldValidator
                  ID="rfvNazwa" runat="server" Text="wymagane" ValidationGroup="JRWA" ErrorMessage="*"
                  ControlToValidate="txtNazwa"></asp:RequiredFieldValidator></td>
            </tr>
            <tr>
              <th>
                <asp:Label ID="lblKategoriaAKM" runat="server" Text="Kategoria archiwalna w kom. macierz."
                  AssociatedControlID="txtKategoriaAKM"></asp:Label></th>
              <td>
                <asp:TextBox ID="txtKategoriaAKM" runat="server" Width="170px" MaxLength="10"></asp:TextBox><asp:RequiredFieldValidator
                  ID="rfvKategoriaAKM" runat="server" Text="wymagane" Visible="False" Enabled="False"
                  ValidationGroup="JRWA" ErrorMessage="*" ControlToValidate="txtKategoriaAKM"></asp:RequiredFieldValidator></td>
            </tr>
            <tr>
              <th>
                <asp:Label ID="lblKategoriaAIK" runat="server" Text="Kategoria archiwalna w innych kom."
                  AssociatedControlID="txtKategoriaAIK"></asp:Label></th>
              <td>
                <asp:TextBox ID="txtKategoriaAIK" runat="server" Width="170px" MaxLength="10"></asp:TextBox><asp:RequiredFieldValidator
                  ID="rfvKategoriaAIK" runat="server" Text="wymagane" Visible="False" Enabled="False"
                  ValidationGroup="JRWA" ErrorMessage="*" ControlToValidate="txtKategoriaAIK"></asp:RequiredFieldValidator></td>
            </tr>
            <tr>
              <th>
                <asp:Label ID="lblUwagi" runat="server" Text="Uwagi:" AssociatedControlID="txtUwagi"></asp:Label></th>
              <td>
                <asp:TextBox ID="txtUwagi" runat="server" Width="95%" Rows="3" 
                      TextMode="MultiLine" MaxLength="500"></asp:TextBox></td>
            </tr>
            <tr>
              <th>
                <asp:Label ID="lblStatus" runat="server" Text="Status:" AssociatedControlID="ckbAktywna"></asp:Label>
              </th>
              <td>
                <asp:CheckBox ID="ckbAktywna" runat="server" Text="Aktywny" Checked="true"></asp:CheckBox></td>
            </tr>
            <tr>
              <td colspan="2">
                <asp:LinkButton ID="btnAdd" runat="server" Text="Dodaj" CommandName="Insert" ValidationGroup="JRWA"></asp:LinkButton>
                <asp:LinkButton ID="btnCancel" OnClick="btnCancel_Click" runat="server" Text="Anuluj"
                  CausesValidation="False"></asp:LinkButton></td>
            </tr>
          </tbody>
        </table>
        </InsertItemTemplate>
        <ItemTemplate>
        <table class="grid fullWidth">
          <tbody>
            <tr>
              <th colspan="2">Pozycja JRWA</th>
            </tr>
            <tr>
              <th>Symbol:</th>
              <td>
                <asp:Label ID="lblParentSymbol" runat="server" Visible="False" Font-Size="Medium" /><asp:Label ID="txtSymbol" runat="server" Text='<%# Eval("symbol") %>'></asp:Label></td>
            </tr>
            <tr>
              <th>Nazwa:</th>
              <td>
                <asp:Label ID="txtNazwa" runat="server" Text='<%# Eval("nazwa") %>'></asp:Label></td>
            </tr>
            <tr>
              <th>Kategoria archiwalna<br />
                w kom. macierz.</th>
              <td>
                <asp:Label ID="txtKategoriaAKM" runat="server" Text='<%# Eval("kategoriaAKM") %>'></asp:Label></td>
            </tr>
            <tr>
              <th>Kategoria archiwalna<br />
                w innych kom.</th>
              <td>
                <asp:Label ID="txtKategoriaAIK" runat="server" Text='<%# Eval("kategoriaAIK") %>'></asp:Label></td>
            </tr>
            <tr>
              <th>Uwagi:</th>
              <td>
                <asp:TextBox ID="txtUwagi" runat="server" Text='<%# Eval("uwagi") %>' ReadOnly="True"
                  BorderStyle="None" Width="95%" Rows="3" TextMode="MultiLine"></asp:TextBox></td>
            </tr>
            <tr>
              <th>Status:</th>
              <td>
                <asp:CheckBox ID="ckbAktywna" runat="server" Text="Aktywny" Enabled="False" Checked='<%# Eval("aktywny") %>'>
                </asp:CheckBox></td>
            </tr>
            <tr>
              <td colspan="2">
                <asp:LinkButton ID="btnEdit" OnClick="btnEdit_Click" runat="server" Text="Edytuj"
                  CommandName="Edit" CausesValidation="False" ValidationGroup="JRWA"></asp:LinkButton></td>
            </tr>
          </tbody>
        </table>
        </ItemTemplate>
    </asp:FormView>
    <asp:LinkButton ID="lnkAddJRWA" runat="server" OnClick="lnkAddJRWA_Click">Dodaj JRWA</asp:LinkButton><br />
    <asp:LinkButton ID="LinkButton1" runat="server" PostBackUrl="~/Aplikacje/PanelAdministracyjny/printJRWA.aspx">Podgl¹d wydruku drzewa JRWA</asp:LinkButton>
  </div>
</asp:Content>
