<%@ Page Language="C#" MasterPageFile="~/MasterPages/SingleColumn.Master" AutoEventWireup="true"
    CodeBehind="NowyRokTworzRejestry.aspx.cs" Inherits="Pemi.Esoda.Web.UI.Aplikacje.PanelAdministracyjny.NowyRokTworzRejestry"
    Title="Nowy rok - tworzenie rejestrów na nowy rok" %>

<%@ Register Src="~/Controls/OperacjePaneluAdministracyjnego.ascx" TagName="OperacjePaneluAdministracyjnego"
    TagPrefix="uc1" %>
<asp:Content ID="Content2" ContentPlaceHolderID="main" runat="server">
    <uc1:OperacjePaneluAdministracyjnego ID="opa1" runat="server" />    
    <div><asp:LinkButton runat="server" ID="lblBack" Text="Powrót" PostBackUrl="~/Aplikacje/PanelAdministracyjny/NowyRok.aspx" /></div>
    <asp:Label runat="server" ID="lblMessage" ForeColor="Red" />
    <fieldset>
        <legend>Tworzenie rejestrów na nowy rok</legend>
        <div style="padding: 5px; float: left; width: 30%;">
        <span>Wybierz wydzia³:</span>
        <asp:TreeView ID="tvGroups" runat="server" DataSourceID="dsxmlGroups" AutoGenerateDataBindings="False"
            ImageSet="Arrows" OnSelectedNodeChanged="tvGroups_SelectedNodeChanged">
            <DataBindings>
                <asp:TreeNodeBinding DataMember="Group" TextField="Text" ValueField="Value" />
            </DataBindings>
            <SelectedNodeStyle CssClass="treeSelectedNode" />
        </asp:TreeView>
        <asp:XmlDataSource ID="dsxmlGroups" runat="server" TransformFile="~/Aplikacje/PanelAdministracyjny/xsltGroups.xslt"
            XPath="Groups/Group" EnableCaching="False"></asp:XmlDataSource>
        </div>
        <div runat="server" id="rightPanel" visible="false">
        <div>
                Rejestry z roku 
                <asp:DropDownList runat="server" 
                ID="ddlAvailableYears" DataTextField="Id" DataValueField="Description" 
                AutoPostBack="True" 
                onselectedindexchanged="ddlAvailableYears_SelectedIndexChanged" />
        </div>
        <div runat="server" id="availableRegistries" visible="false" style="padding: 5px; margin-left: 32%;">        
        <asp:CheckBoxList runat="server" ID="registries" DataTextField="Title" 
                DataValueField="ID" onprerender="registries_PreRender"/>
        <br />
                <fieldset style="width: 300px;">
                    <legend>Kopiuj na nowy rok</legend>
                    <div style="padding: 5px;">
                        <asp:ValidationSummary ID="ValidationSummary1" runat="server" ValidationGroup="createGroup" />
                        <asp:Label ID="Label1" runat="server" AssociatedControlID="newYear" Text="Podaj rok docelowy:" />
                        <asp:TextBox runat="server" ID="newYear" Width="45px" />
                        <asp:CompareValidator ID="CompareValidator1" runat="server" ControlToValidate="newYear" Operator="DataTypeCheck" ValidationGroup="createGroup" Type="Integer" ErrorMessage="Z³y format roku." Text="*"/>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="newYear" ValidationGroup="createGroup" ErrorMessage="Rok docelowy jest wymagany." Text="*"/>
                        <asp:CustomValidator runat="server" ID="NewYearValidator" ValidationGroup="createGroup" ErrorMessage="Rok docelowy musi byæ inny ni¿ rok rejestru."  Text="*"
                ControlToValidate="newYear" onservervalidate="NewYearValidator_ServerValidate" />
                        <br />
                        <asp:LinkButton ID="LinkButton1" runat="server" Text="utwórz" onclick="create_Click" CommandArgument="create" ValidationGroup="createGroup" />
                    </div>
                </fieldset>
        
        </div>
        <div runat="server" id="noAvailableRegistries" visible="false" style="padding: 5px; margin-left: 32%;">Brak rejestrów.</div>
        </div>
        <br />
    </fieldset>
</asp:Content>
